### PR TITLE
Naming Conventions

### PR DESCRIPTION
**Pull request by wickedOne**
i ran some tests to see whether this coding standard enforces all things mentioned in the [naming conventions](http://symfony.com/doc/current/contributing/code/standards.html#naming-conventions) section of symfony's coding standard and made several modifications accordingly. 

this pull request makes sure that the following additional guidelines are met:
- Use camelCase, not underscores, for function and method names
- Use namespaces for all classes
- Prefix abstract classes with Abstract
- Suffix traits with Trait
- Suffix exceptions with Exception

###### note:
this might cause a bit of a stirr as the guidelines mentioned above haven't been enforced in the past thus people using this standard potentially end up with a bunch of phpcs errors and the need to refactor parts of their codebase (at least the main repositories i'm working on will require quite a bit of work to comply) .

### CODE REVIEW

**Comment by wickedOne** [comment]
@djoos any reason why this one doesn't get merged nor closed?

**Comment by djoos** [comment]
Hi @wickedOne,

I actually haven't been able to have a proper look at the PR yet... :-/

Kind regards,
David

**Comment by wickedOne** [comment]
hi @djoos 
no problem, was just wondering & considering setting up a clone meanwhile…

just let me know, 
cheers
w

**Comment by djoos** [comment]
Peehaps it's best to make use of your PR-fork for now until I get the chance to review the PR and get it merged into the master-branch...

Hope this helps!

Kind regards,
David

**Comment by wickedOne** [comment]
ok, i'll set up a clone as there are more sniffs on the way and it might grow into a too big a pull request…
once you've got a bit more time on your hands i'll offer them in seperate pull requests to this repository

cheers
w

**Comment by djoos** [comment]
Hi @wickedOne,

I think the best way forward is to put each change into a relevantly named branch - do create a PR for each of these branches so we can review and get them merged in ASAP.

Hope this helps!

Kind regards,
David

**Comment by djoos** [comment]
Thanks for your contribution @wickedOne - sorry for the delay in getting this PR merged...

Kind regards,
David

**Pull request merged**
