### PR TITLE
Fix unwanted return tag error with closure statements

### LINKED ISSUE #33: Missing return tag from closure
phpcs reports a missing return tag if the method has no return value but contains a closure which returns a value.

For example, this function

    /**
     * @param \Symfony\Component\Form\FormEvent $event
     */
    public function onPreSetData(FormEvent $event)
    {
        $form = $event->getForm();

        $form->add(
            'project',
            'entity',
            [
                'class' => 'AppBundle:Project',
                'choice_label' => 'name',
                'query_builder' => function (ProjectRepository $repository) {
                        return $repository->queryAll();
                },
                'empty_value' => 'search.all',
                'required' => false,
                'label' => 'project',
                'multiple' => true,
                'expanded' => false,
            ]
        );
    }

triggers the error `Missing @return tag in function comment`

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #33.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@djoos I don't understand the error: https://travis-ci.org/escapestudios/Symfony2-coding-standard/jobs/87933941#L134

Could you please give me a clue?

**Comment by djoos** [comment]
Hi @Soullivaneuh,

a very quick reply here...

"PHP Fatal error:  Cannot redeclare class FunctionCommentUnitTest in /home/travis/build/escapestudios/Symfony2-coding-standard/Symfony2/Tests/Commenting/FunctionCommentUnitTest.php on line 56"
FunctionCommentUnitTest.php is already declared as part of [SquizLabs' PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer/blob/fe45ad6fc25c02566795145999744a13d838fc15/package.xml#L865)...

Hope this helps!

Kind regards,
David

**Comment by Soullivaneuh** [comment]
@djoos Yes, this is what I understood. That I don't know, it's how to solve it.

How to test my override? Can't be possible?

**Comment by Soullivaneuh** [comment]
bump

**Comment by wickedOne** [comment]
prefix your classname with the standard and section (e.g. ``Symfony2_Tests_Commenting_FunctionCommentUnitTest``). 
apparently there already is a class named ``FunctionCommentUnitTest`` and as the tests are not namespaced…

**Comment by Soullivaneuh** [comment]
@wickedOne Thanks for the tip, will try this.

**Comment by Soullivaneuh** [comment]
@djoos Should be OK now. :+1:

**Comment by Soullivaneuh** [comment]
Tests fixed, ready to merge!

**Comment by djoos** [comment]
Thanks for your contribution @Soullivaneuh!

**Comment by Soullivaneuh** [comment]
Thanks for merging. :+1: 

Could we please have a new patch tag for this? :-)

**Comment by djoos** [comment]
Here you go: [2.8.1](https://github.com/escapestudios/Symfony2-coding-standard/releases/tag/2.8.1)!

**Pull request merged**
