### PR TITLE
Update readme with more detailed description of installation and usage

### PR DESCRIPTION
**Pull request by Craige**
Added details for installation both globally and as a part of a project.

Also added a nice bit about using the Symfony2 standard as part of a Symfony2 project. It's not as easy as it would seem. With the method outlined in the README, you can remove the following line from the standard's ``ruleset.xml``, as it doesn't belong as part of the standard, but is rather project specific (You can still use the Symfony2 standard on a project that isn't Symfony2, right?)

    <exclude-pattern>*/Resources/*</exclude-pattern>

Sorry there's like 12 commits to update this. I was all over the place and editing from the GitHub interface.

### CODE REVIEW

**Comment by jfx** [comment]
Hello,
For a symfony project, I think that the easiest way once you have installed "Symfony2-coding-standard" 
with composer is to run the command in your project directory :
```bash
bin/phpcs  --standard=vendor/escapestudios/symfony2-coding-standard/escapestudios/Symfony2-coding-standard/Symfony2/ --extensions=php src/ 
```

**Comment by Craige** [comment]
@jfx Why exclude all other directories? Symfony is meant to be flexible.

It would be better to only filter out stuff that you don't want to check, and check everything else. For example, you are able to write PHP files in `app` to override files from vendor bundles. Also, you may write something funky and one-off in `/web`. This approach also allows you to turn off specific rules for one project, or one rule for one file in a project. This method is flexible.

**Comment by wickedOne** [comment]
@Craige you can [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) all those commits into one if you want to…

**Comment by Craige** [comment]
Yes. I'll squash this and clean it up.

**Comment by Craige** [comment]
Squashed

**Comment by djoos** [comment]
Thanks for your contribution @Craige - I did end up stripping out some details on the installation as I didn't think we would have to go into such detail, especially as Composer and PHP_CodeSniffer are not part of this repository.

Kind regards,
David

**Pull request merged**
