### PR TITLE
Make MultiLineArrayCommaSniff work for the short-array syntax '[]'

### LINKED ISSUE #17: MultiLineArrayComma sniff doesn't work for the short array syntax []
The MultiLineArrayCommaSniff does not work for arrays defined with the not-so-new short-array syntax:

    $array = [
        'foo',
        'bar'
    ];

### PR DESCRIPTION
**Pull request by Craige**
Fixes #17.

### CODE REVIEW

**Comment by Craige** [comment]
Not sure how to run the unit test, or what standard you use to verify code. This should probably be documented somewhere.

**Comment by wickedOne** [comment]
as far as i can see neither Symfony2/Tests/Arrays/MultiLineArrayComma.php nor Symfony2/Tests/Arrays/MultiLineArrayComma.inc add any value or functionality (no assertions are made). 
apart from that you might want to squash your commits into one, here's a nice [style guide](https://github.com/agis-/git-style-guide) for some pointers on that.

**Comment by Craige** [comment]
@wickedOne - To be honest I'm winging the Test. From what I understand, it's just a simple test that makes sure an error is thrown on line 5 and line 22. I'm just assembling it from looking at some examples in the PHP_CodeSniffer repository.

In any case, I can't get the tests to run at all.

```
phpunit:
     [exec] Current OS is Mac OS X
     [exec] Executing 'phpunit' with arguments:
     [exec] '--filter=Symfony2_*'
     [exec] '/Users/craigeleeder/Source/symfony2-coding-standard/vendor/squizlabs/php_codesniffer/tests/AllTests.php'
     [exec]
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
     [exec] Cannot open file "/Users/craigeleeder/Source/symfony2-coding-standard/vendor/squizlabs/php/codesniffer/tests/AllTests.php".
     [exec]
```

The 'tests' direcotry doesn't exist at all when checked out with composer.

**Comment by wickedOne** [comment]
first of all: i do appreciate your contributions and the effort, but adding a test without being able to run the actual test (which makes it a best guess) does not make any sense…
locally i've got the same error as you described. i'll have a look and get those unit tests up and running again and perhaps @djoos can make tests and code coverage mandatory for contributions

**Comment by Craige** [comment]
Of course. I initiated the PR to rely on Travis CI to to run the build for me, as I mentioned in my first comment that i was unsure how to run these myself. Sorry for the confusion.

**Comment by Craige** [comment]
@wickedOne I fixed this locally by adding a new argument to the vendor task

```
    <target name="vendor" description="Load composer repositories" depends="composer">
        <exec executable="composer" failonerror="true">
            <arg value="install" />
            <arg value="--prefer-source" />
        </exec>
    </target>
```
This solves the problem of the /tests directory not existing ( it doesn't exist in the zip download from github), but Im' having other problems now.

**Comment by djoos** [comment]
Re: missing tests-directory
I had this issue last week as well. Event though the tests-directory resided in [the repo](https://github.com/squizlabs/PHP_CodeSniffer/), they were not present after running composer...
When locking squizlabs/PHP_CodeSniffer to ~2.2.0 (=2.0.*) rather than ~2.0 (=2.*) I was able to get round it. #13 

Alternatively @Craige's suggestion using --prefer-source should do the trick as well.

**Comment by djoos** [comment]
Thanks for your contribution @Craige!

Kind regards,
David

**Pull request merged**
