### PR TITLE
changed MultiLineArrayCommaSniff to support comments

### PR DESCRIPTION
**Pull request by rweich**
issue #24

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
:+1: 

ping @djoos: Can you please merge this one? This is a must have!

**Comment by djoos** [comment]
Thanks for your contribution @rweich!

Kind regards,
David

**Comment by Soullivaneuh** [comment]
Thanks! :+1: 

Could you please bump a new patch release? :-)

**Comment by djoos** [comment]
I was waiting for Travis to give me the green light ;-)

...2.6.0 has now been released!

Kind regards,
David

**Pull request merged**
